"use client";
import { useState } from "react";
import { residentialCommand, RESIDENTIAL_PRESETS, suggestResidentialTypes, type ResidentialParameters } from "@/lib/ai/modeling/allocation";
import { allocateBuilding } from "@/lib/ai/modeling/footprint";
import AiFootprintCanvas from "./AiFootprintCanvas";
import { validateSketches } from "@/lib/ai/modeling/sketch";
import { polygonArea } from "@/lib/ai/modeling/footprint";

export default function AiBuildingPresets({disabled,heightMm,thicknessMm,onChoose,onCreate}:{disabled:boolean;heightMm:number;thicknessMm:number;onChoose:(command:string,p:ResidentialParameters)=>void;onCreate:(command:string,p:ResidentialParameters)=>void}){
  const [selected,setSelected]=useState<number|null>(null);
  const [plotArea,setPlotArea]=useState(0);
  const [p,setP]=useState<ResidentialParameters>({variant:"apartment",bedrooms:2,bedroomAreaM2:20,furnished:true});
  let result:ReturnType<typeof allocateBuilding>|null=null,error="";
  const validate=(next:ResidentialParameters)=>{if(next.apartmentFloors!==undefined||next.apartmentsPerFloor!==undefined||next.bedroomsPerApartment!==undefined)return null;if(next.sketches){validateSketches(next.sketches);const area=next.sketches.reduce((sum,s)=>sum+polygonArea(s.points)/1e6,0);if(next.totalAreaM2!==undefined&&Math.abs(area-next.totalAreaM2)>.1)throw new Error(`Drawn floors give ${area.toFixed(1)} mÂ². Update the total or adjust the lines.`);return null;}return allocateBuilding(next,heightMm,thicknessMm);};
  if(selected!==null)try{result=validate(p);}catch(e){error=e instanceof Error?e.message:"Check room sizes.";}
  const update=(next:ResidentialParameters)=>{setP(next);try{validate(next);onChoose(residentialCommand(next),next);}catch{onChoose("",next);}};
  const fields=[{key:"totalAreaM2",label:"Total internal area",min:30,max:2000},{key:"bedroomAreaM2",label:"Each bedroom",min:1,max:100},{key:"livingAreaM2",label:"Living / dining",min:10,max:300},{key:"kitchenAreaM2",label:"Kitchen",min:6,max:300},{key:"bathroomAreaM2",label:"Each bathroom",min:4,max:300},{key:"widthM",label:"Building width Â· m",min:4,max:80},{key:"lengthM",label:"Building length Â· m",min:4,max:80}]as const;
  const allocation=result?.allocation;
  return <section className="ai-building-presets" aria-label="Building examples">
    <div className="ai-area-fields"><label>Plot / buildable area · m²<input aria-label="Plot area" type="number" min={30} step="1" value={plotArea||""} placeholder="Enter plot area first" onChange={e=>setPlotArea(Number(e.target.value)||0)} /></label></div>
    {plotArea>0&&<p className="ai-text-muted" aria-live="polite">Suggested for {plotArea} m²: {suggestResidentialTypes(plotArea).map(s=>s.label).join(" · ")}</p>}
    <div className="ai-suggestion-row" aria-label="Choose a building">{RESIDENTIAL_PRESETS.map((item,index)=><button key={item.label} type="button" aria-pressed={selected===index} disabled={disabled} onClick={()=>{setSelected(index);const style=item.layoutStyle;update({variant:item.variant,bedrooms:item.bedrooms,bedroomAreaM2:20,furnished:true,layoutStyle:style,cultureStyle:"cultureStyle" in item?item.cultureStyle:"standard",roofStyle:"roofStyle" in item?item.roofStyle:item.variant==="apartment"?undefined:"modern-flat",separateKitchen:"separateKitchen" in item?item.separateKitchen:item.variant==="apartment",ensuiteBathrooms:"ensuiteBathrooms" in item?item.ensuiteBathrooms:item.variant==="apartment",footprint:"footprint" in item?item.footprint:style==="courtyard"||style==="central"?"u":style==="corner"?"l":"rectangle",footprintPoints:"footprintPoints" in item?item.footprintPoints.map(point=>({...point})):undefined,garage:"garage" in item?item.garage:item.variant==="apartment"?"none":"enclosed",gardenAreaM2:"gardenAreaM2" in item?item.gardenAreaM2:item.variant==="apartment"?0:40,...("totalAreaM2" in item?{totalAreaM2:item.totalAreaM2}:{}),...( "apartmentFloors" in item?{apartmentFloors:item.apartmentFloors,apartmentsPerFloor:item.apartmentsPerFloor,bedroomsPerApartment:item.bedroomsPerApartment}: {})});}}>{item.label}</button>)}</div>
    {selected!==null&&<details open className="ai-building-options"><summary>{RESIDENTIAL_PRESETS[selected].label} Â· choose layout</summary>
      <AiFootprintCanvas parameters={p} onChange={update} disabled={disabled} building={result}/>
      <label className="ai-area-fields"><span>Design style</span><select aria-label="Design style" value={p.layoutStyle??"linear"} disabled={disabled} onChange={e=>{const layoutStyle=e.target.value as ResidentialParameters["layoutStyle"];update({...p,layoutStyle,footprint:layoutStyle==="courtyard"||layoutStyle==="central"?"u":layoutStyle==="corner"?"l":"rectangle"});}}><option value="linear">Linear rooms</option><option value="courtyard">Courtyard / U plan</option><option value="corner">Corner / L plan</option><option value="split">Split-wing plan</option><option value="central">Central core plan</option></select></label>
      <div className="ai-area-fields"><label>Planning tradition<select aria-label="Planning tradition" value={p.cultureStyle??"standard"} disabled={disabled} onChange={e=>update({...p,cultureStyle:e.target.value as ResidentialParameters["cultureStyle"]})}><option value="standard">Contemporary</option><option value="vastu">India Â· Vastu zoning</option><option value="german">German planning</option></select></label>{p.variant!=="apartment"&&<label>Roof style<select aria-label="Roof style" value={p.roofStyle??"modern-flat"} disabled={disabled} onChange={e=>update({...p,roofStyle:e.target.value as ResidentialParameters["roofStyle"]})}><option value="modern-flat">Modern flat</option><option value="german-gable">German gable Â· Satteldach</option><option value="german-hip">German hip roof</option><option value="mansard">Mansard roof</option></select></label>}</div>
      <div className="ai-area-fields">{fields.map(f=><label key={f.key}>{f.label}{!f.key.endsWith("M")&&" Â· mÂ²"}<input type="number" aria-label={`${f.label}${f.key.endsWith("M")?"":" in square metres"}`} min={f.min} max={f.key==="totalAreaM2"?20000:f.max} step="0.5" aria-invalid={f.key==="bedroomAreaM2"&&(p.bedroomAreaM2??20)<11} disabled={disabled} value={p[f.key]??""} placeholder={f.key==="bedroomAreaM2"?"20":f.key==="totalAreaM2"?String(allocation?.recommendedAreaM2??"Auto"):"Auto"} onChange={e=>update({...p,[f.key]:e.target.value===""?undefined:Number(e.target.value)})}/></label>)}</div>
      {p.apartmentFloors !== undefined && <div className="ai-area-fields ai-apartment-block-fields"><label>Apartment floors<input aria-label="Apartment floors" type="number" min={1} max={12} step={1} value={p.apartmentFloors} disabled={disabled} onChange={e=>update({...p,apartmentFloors:Number(e.target.value)})}/></label><label>Homes per floor<input aria-label="Homes per floor" type="number" min={2} max={10} step={1} value={p.apartmentsPerFloor??4} disabled={disabled} onChange={e=>update({...p,apartmentsPerFloor:Number(e.target.value)})}/></label><label>Bedrooms per home<select aria-label="Bedrooms per apartment" value={p.bedroomsPerApartment??2} disabled={disabled} onChange={e=>update({...p,bedroomsPerApartment:Number(e.target.value) as 1|2|3,bedrooms:Number(e.target.value)})}><option value={1}>Single bedroom</option><option value={2}>Double bedroom</option><option value={3}>Triple bedroom</option></select></label></div>}
      {(p.bedroomAreaM2??20)<11&&<p role="alert" className="ai-error">This bedroom is too small for the default layout. Choose at least 11â€“14 mÂ²; recommended 18 mÂ². Your value has not been changed.</p>}
      <p className="ai-text-muted">Blank values adapt automatically. Width/length measure inside perimeter walls. Total covers all floors; garage and garden are additional.</p>
      <label className="ai-layout-toggle"><input type="checkbox" checked={p.furnished!==false} disabled={disabled} onChange={e=>update({...p,furnished:e.target.checked})}/> Basic furniture</label>
      {p.variant === "apartment" && <div className="ai-area-fields"><label className="ai-layout-toggle"><input type="checkbox" checked={p.separateKitchen??true} disabled={disabled} onChange={e=>update({...p,separateKitchen:e.target.checked})}/> Separate kitchen room</label><label className="ai-layout-toggle"><input type="checkbox" checked={p.ensuiteBathrooms??true} disabled={disabled} onChange={e=>update({...p,ensuiteBathrooms:e.target.checked})}/> Ensuite bathrooms</label></div>}
      <details><summary>MEP options</summary><label className="ai-layout-toggle"><input type="checkbox" checked={p.underfloorHeating??false} disabled={disabled} onChange={e=>update({...p,underfloorHeating:e.target.checked})}/> Underfloor heating</label><div className="ai-area-fields"><label>Water piping<select aria-label="Water piping placement" value={p.piping??"none"} disabled={disabled} onChange={e=>update({...p,piping:e.target.value as ResidentialParameters["piping"]})}><option value="none">No piping</option><option value="underfloor">Under floor</option><option value="ceiling">Below roof / ceiling</option></select></label><label>Ventilation ducts<select aria-label="Ventilation ducts" value={p.ducts??"none"} disabled={disabled} onChange={e=>update({...p,ducts:e.target.value as ResidentialParameters["ducts"]})}><option value="none">No ducts</option><option value="ceiling">Below roof / ceiling</option></select></label></div><p className="ai-text-muted">Concept routes and equipment; system sizing and connections need design review.</p></details>
      {p.variant!=="apartment"&&<details open><summary>Garage and garden</summary><div className="ai-area-fields"><label>Garage<select aria-label="Garage type" value={p.garage??"enclosed"} disabled={disabled} onChange={e=>update({...p,garage:e.target.value as ResidentialParameters["garage"]})}><option value="none">No garage</option><option value="open">Open carport</option><option value="enclosed">Enclosed Â· overhead door</option></select></label>{([{key:"garageWidthM",label:"Garage width Â· m",min:3,default:3.5},{key:"garageDepthM",label:"Garage length Â· m",min:5.5,default:6},{key:"gardenAreaM2",label:"Garden area Â· mÂ²",min:0,default:40}]as const).map(f=><label key={f.key}>{f.label}<input aria-label={f.label} type="number" min={f.min} step=".5" disabled={disabled} value={p[f.key]??f.default} onChange={e=>update({...p,[f.key]:Number(e.target.value)})}/></label>)}</div></details>}
      {error&&<p role="alert" className="ai-error">{error}</p>}
      {p.sketches&&<p className="ai-text-muted">Custom drawing Â· {p.sketches.length} floors Â· {p.sketches.reduce((sum,s)=>sum+polygonArea(s.points)/1e6,0).toFixed(1)} mÂ². Drawn dimensions determine room sizes.</p>}
      {allocation&&<div className="ai-area-summary" aria-live="polite"><strong>{Number((allocation.totalAreaM2+(result?.extraAreaM2??0)).toFixed(1))} mÂ² total Â· {allocation.floors} floor{allocation.floors>1?"s":""}</strong><p>Bedrooms {Number(allocation.bedroomTotalM2.toFixed(1))} Â· Living {Number(allocation.livingTotalM2.toFixed(1))} Â· Kitchen {Number(allocation.kitchenTotalM2.toFixed(1))} Â· Baths {Number(allocation.bathroomTotalM2.toFixed(1))} mÂ²{(result?.extraAreaM2??0)>.1?` Â· Additional living wings ${result!.extraAreaM2.toFixed(1)} mÂ²`:""}</p></div>}
      <div className="ai-layout-actions"><button type="button" className="ai-secondary-button" disabled={disabled} onClick={()=>update({...p,layoutSeed:Math.floor(Math.random()*1000000)})}>Refresh / Shuffle layout</button><button type="button" className="ai-create-layout" disabled={disabled||!!error||(p.bedroomAreaM2??20)<11} onClick={()=>onCreate(residentialCommand(p),p)}>Create this layout</button></div>
    </details>}
  </section>;
}
