"use client";
import { useState } from "react";
import { residentialCommand, RESIDENTIAL_PRESETS, type ResidentialParameters } from "@/lib/ai/modeling/allocation";
import { allocateBuilding } from "@/lib/ai/modeling/footprint";
import AiFootprintCanvas from "./AiFootprintCanvas";
import { validateSketches } from "@/lib/ai/modeling/sketch";
import { polygonArea } from "@/lib/ai/modeling/footprint";

export default function AiBuildingPresets({disabled,heightMm,thicknessMm,onChoose,onCreate}:{disabled:boolean;heightMm:number;thicknessMm:number;onChoose:(command:string,p:ResidentialParameters)=>void;onCreate:(command:string,p:ResidentialParameters)=>void}){
  const [selected,setSelected]=useState<number|null>(null);
  const [p,setP]=useState<ResidentialParameters>({variant:"apartment",bedrooms:2,bedroomAreaM2:20,furnished:true});
  let result:ReturnType<typeof allocateBuilding>|null=null,error="";
  const validate=(next:ResidentialParameters)=>{if(next.apartmentFloors!==undefined||next.apartmentsPerFloor!==undefined||next.bedroomsPerApartment!==undefined)return null;if(next.sketches){validateSketches(next.sketches);const area=next.sketches.reduce((sum,s)=>sum+polygonArea(s.points)/1e6,0);if(next.totalAreaM2!==undefined&&Math.abs(area-next.totalAreaM2)>.1)throw new Error(`Drawn floors give ${area.toFixed(1)} m². Update the total or adjust the lines.`);return null;}return allocateBuilding(next,heightMm,thicknessMm);};
  if(selected!==null)try{result=validate(p);}catch(e){error=e instanceof Error?e.message:"Check room sizes.";}
  const update=(next:ResidentialParameters)=>{setP(next);try{validate(next);onChoose(residentialCommand(next),next);}catch{onChoose("",next);}};
  const fields=[{key:"totalAreaM2",label:"Total internal area",min:30,max:2000},{key:"bedroomAreaM2",label:"Each bedroom",min:1,max:100},{key:"livingAreaM2",label:"Living / dining",min:10,max:300},{key:"kitchenAreaM2",label:"Kitchen",min:6,max:300},{key:"bathroomAreaM2",label:"Each bathroom",min:4,max:300},{key:"widthM",label:"Building width · m",min:4,max:80},{key:"lengthM",label:"Building length · m",min:4,max:80}]as const;
  const allocation=result?.allocation;
  return <section className="ai-building-presets" aria-label="Building examples">
    <div className="ai-suggestion-row" aria-label="Choose a building">{RESIDENTIAL_PRESETS.map((item,index)=><button key={item.label} type="button" aria-pressed={selected===index} disabled={disabled} onClick={()=>{setSelected(index);const style=item.layoutStyle;update({variant:item.variant,bedrooms:item.bedrooms,bedroomAreaM2:20,furnished:true,layoutStyle:style,separateKitchen:"separateKitchen" in item?item.separateKitchen:item.variant==="apartment",ensuiteBathrooms:"ensuiteBathrooms" in item?item.ensuiteBathrooms:item.variant==="apartment",footprint:style==="courtyard"||style==="central"?"u":style==="corner"?"l":"rectangle",garage:item.variant==="apartment"?"none":"enclosed",gardenAreaM2:item.variant==="apartment"?0:40,...("apartmentFloors" in item?{apartmentFloors:item.apartmentFloors,apartmentsPerFloor:item.apartmentsPerFloor,bedroomsPerApartment:item.bedroomsPerApartment}: {})});}}>{item.label}</button>)}</div>
    {selected!==null&&<details open className="ai-building-options"><summary>{RESIDENTIAL_PRESETS[selected].label} · choose layout</summary>
      <AiFootprintCanvas parameters={p} onChange={update} disabled={disabled} building={result}/>
      <label className="ai-area-fields"><span>Design style</span><select aria-label="Design style" value={p.layoutStyle??"linear"} disabled={disabled} onChange={e=>{const layoutStyle=e.target.value as ResidentialParameters["layoutStyle"];update({...p,layoutStyle,footprint:layoutStyle==="courtyard"||layoutStyle==="central"?"u":layoutStyle==="corner"?"l":"rectangle"});}}><option value="linear">Linear rooms</option><option value="courtyard">Courtyard / U plan</option><option value="corner">Corner / L plan</option><option value="split">Split-wing plan</option><option value="central">Central core plan</option></select></label>
      <div className="ai-area-fields">{fields.map(f=><label key={f.key}>{f.label}{!f.key.endsWith("M")&&" · m²"}<input type="number" aria-label={`${f.label}${f.key.endsWith("M")?"":" in square metres"}`} min={f.min} max={f.key==="totalAreaM2"?20000:f.max} step="0.5" aria-invalid={f.key==="bedroomAreaM2"&&(p.bedroomAreaM2??20)<11} disabled={disabled} value={p[f.key]??""} placeholder={f.key==="bedroomAreaM2"?"20":f.key==="totalAreaM2"?String(allocation?.recommendedAreaM2??"Auto"):"Auto"} onChange={e=>update({...p,[f.key]:e.target.value===""?undefined:Number(e.target.value)})}/></label>)}</div>
      {p.apartmentFloors !== undefined && <div className="ai-area-fields ai-apartment-block-fields"><label>Apartment floors<input aria-label="Apartment floors" type="number" min={1} max={12} step={1} value={p.apartmentFloors} disabled={disabled} onChange={e=>update({...p,apartmentFloors:Number(e.target.value)})}/></label><label>Homes per floor<input aria-label="Homes per floor" type="number" min={2} max={10} step={1} value={p.apartmentsPerFloor??4} disabled={disabled} onChange={e=>update({...p,apartmentsPerFloor:Number(e.target.value)})}/></label><label>Bedrooms per home<select aria-label="Bedrooms per apartment" value={p.bedroomsPerApartment??2} disabled={disabled} onChange={e=>update({...p,bedroomsPerApartment:Number(e.target.value) as 1|2|3,bedrooms:Number(e.target.value)})}><option value={1}>Single bedroom</option><option value={2}>Double bedroom</option><option value={3}>Triple bedroom</option></select></label></div>}
      {(p.bedroomAreaM2??20)<11&&<p role="alert" className="ai-error">This bedroom is too small for the default layout. Choose at least 11–14 m²; recommended 18 m². Your value has not been changed.</p>}
      <p className="ai-text-muted">Blank values adapt automatically. Width/length measure inside perimeter walls. Total covers all floors; garage and garden are additional.</p>
      <label className="ai-layout-toggle"><input type="checkbox" checked={p.furnished!==false} disabled={disabled} onChange={e=>update({...p,furnished:e.target.checked})}/> Basic furniture</label>
      {p.variant === "apartment" && <div className="ai-area-fields"><label className="ai-layout-toggle"><input type="checkbox" checked={p.separateKitchen??true} disabled={disabled} onChange={e=>update({...p,separateKitchen:e.target.checked})}/> Separate kitchen room</label><label className="ai-layout-toggle"><input type="checkbox" checked={p.ensuiteBathrooms??true} disabled={disabled} onChange={e=>update({...p,ensuiteBathrooms:e.target.checked})}/> Ensuite bathrooms</label></div>}
      <details><summary>MEP options</summary><label className="ai-layout-toggle"><input type="checkbox" checked={p.underfloorHeating??false} disabled={disabled} onChange={e=>update({...p,underfloorHeating:e.target.checked})}/> Underfloor heating</label><div className="ai-area-fields"><label>Water piping<select aria-label="Water piping placement" value={p.piping??"none"} disabled={disabled} onChange={e=>update({...p,piping:e.target.value as ResidentialParameters["piping"]})}><option value="none">No piping</option><option value="underfloor">Under floor</option><option value="ceiling">Below roof / ceiling</option></select></label><label>Ventilation ducts<select aria-label="Ventilation ducts" value={p.ducts??"none"} disabled={disabled} onChange={e=>update({...p,ducts:e.target.value as ResidentialParameters["ducts"]})}><option value="none">No ducts</option><option value="ceiling">Below roof / ceiling</option></select></label></div><p className="ai-text-muted">Concept routes and equipment; system sizing and connections need design review.</p></details>
      {p.variant!=="apartment"&&<details open><summary>Garage and garden</summary><div className="ai-area-fields"><label>Garage<select aria-label="Garage type" value={p.garage??"enclosed"} disabled={disabled} onChange={e=>update({...p,garage:e.target.value as ResidentialParameters["garage"]})}><option value="none">No garage</option><option value="open">Open carport</option><option value="enclosed">Enclosed · overhead door</option></select></label>{([{key:"garageWidthM",label:"Garage width · m",min:3,default:3.5},{key:"garageDepthM",label:"Garage length · m",min:5.5,default:6},{key:"gardenAreaM2",label:"Garden area · m²",min:0,default:40}]as const).map(f=><label key={f.key}>{f.label}<input aria-label={f.label} type="number" min={f.min} step=".5" disabled={disabled} value={p[f.key]??f.default} onChange={e=>update({...p,[f.key]:Number(e.target.value)})}/></label>)}</div></details>}
      {error&&<p role="alert" className="ai-error">{error}</p>}
      {p.sketches&&<p className="ai-text-muted">Custom drawing · {p.sketches.length} floors · {p.sketches.reduce((sum,s)=>sum+polygonArea(s.points)/1e6,0).toFixed(1)} m². Drawn dimensions determine room sizes.</p>}
      {allocation&&<div className="ai-area-summary" aria-live="polite"><strong>{Number((allocation.totalAreaM2+(result?.extraAreaM2??0)).toFixed(1))} m² total · {allocation.floors} floor{allocation.floors>1?"s":""}</strong><p>Bedrooms {Number(allocation.bedroomTotalM2.toFixed(1))} · Living {Number(allocation.livingTotalM2.toFixed(1))} · Kitchen {Number(allocation.kitchenTotalM2.toFixed(1))} · Baths {Number(allocation.bathroomTotalM2.toFixed(1))} m²{(result?.extraAreaM2??0)>.1?` · Additional living wings ${result!.extraAreaM2.toFixed(1)} m²`:""}</p></div>}
      <button type="button" className="ai-create-layout" disabled={disabled||!!error||(p.bedroomAreaM2??20)<11} onClick={()=>onCreate(residentialCommand(p),p)}>Create this layout</button>
    </details>}
  </section>;
}
