"use client";
import type { ResidentialParameters } from "@/lib/ai/modeling/allocation";

export default function AiHomeRooms({ parameters: p, disabled, onChange, areasOnly = false }: { parameters: ResidentialParameters; disabled: boolean; onChange: (p: ResidentialParameters) => void; areasOnly?: boolean }) {
  const change = (patch: Partial<ResidentialParameters>) => onChange({ ...p, ...patch, sketches: undefined, totalAreaM2: undefined });
  return <div className="ai-home-rooms">
    {!areasOnly && <><div className="ai-area-fields"><label><span>Bedrooms</span><select aria-label="Home bedroom count" disabled={disabled} value={p.bedrooms} onChange={e => { const bedrooms = Number(e.target.value); change({ bedrooms, bedroomTypes: Array.from({ length: bedrooms }, (_, i) => p.bedroomTypes?.[i] ?? "standard"), bedroomEnsuites: Array.from({ length: bedrooms }, (_, i) => p.bedroomEnsuites?.[i] ?? false), bedroomAreasM2: Array.from({ length: bedrooms }, (_, i) => p.bedroomAreasM2?.[i] ?? p.bedroomAreaM2 ?? 14) }); }}>{[1,2,3,4,5,6].map(n => <option key={n}>{n}</option>)}</select></label><label><span>Common bathrooms</span><select aria-label="Common bathroom count" disabled={disabled} value={p.bathroomCount ?? (p.variant === "duplex" ? 2 : 1)} onChange={e => change({ bathroomCount: Number(e.target.value) })}>{[1,2,3,4].filter(n => p.variant !== "duplex" || n >= 2).map(n => <option key={n}>{n}</option>)}</select></label><label><span>Guest bathroom</span><select aria-label="Guest bathroom concept" disabled={disabled} value={!p.guestBathroom ? "none" : p.guestBathroomShower ? "shower" : "wc"} onChange={e => change({ guestBathroom: e.target.value !== "none", guestBathroomShower: e.target.value === "shower" })}><option value="none">None</option><option value="wc">Guest WC</option><option value="shower">Guest WC + shower</option></select></label><label><span>Kitchen</span><select aria-label="Kitchen concept" disabled={disabled} value={p.separateKitchen ? "separate" : "combined"} onChange={e => change({ separateKitchen: e.target.value === "separate" })}><option value="separate">Separate kitchen</option><option value="combined">Kitchen + living room</option></select></label></div><p className="ai-text-muted">Master bedrooms include an ensuite inside the room. Kids can use their own bathroom or a common bathroom.</p></>}
    {Array.from({length:p.bedrooms},(_,i)=><div key={i} className="ai-home-room-row"><strong>Room {i+1}</strong>{!areasOnly && <><label><span>Bedroom type</span><select aria-label={`Bedroom ${i+1} type`} disabled={disabled} value={p.bedroomTypes?.[i]??"standard"} onChange={e=>{const type=e.target.value as "standard"|"master"|"kids";const types=Array.from({length:p.bedrooms},(_,j)=>j===i?type:p.bedroomTypes?.[j]??"standard");const ensuite=Array.from({length:p.bedrooms},(_,j)=>j===i?type==="master":p.bedroomEnsuites?.[j]??false);const areas=Array.from({length:p.bedrooms},(_,j)=>j===i?type==="master"?20:type==="kids"?11:14:p.bedroomAreasM2?.[j]??p.bedroomAreaM2??14);change({bedroomTypes:types,bedroomEnsuites:ensuite,bedroomAreasM2:areas,bedroomAreaM2:areas.reduce((s,a)=>s+a,0)/areas.length});}}><option value="standard">Bedroom</option><option value="master">Master bedroom</option><option value="kids">Kids room</option></select></label><label><span>Bathroom access</span><select aria-label={`Bedroom ${i+1} bathroom`} disabled={disabled||p.bedroomTypes?.[i]==="master"} value={p.bedroomTypes?.[i]==="master"||p.bedroomEnsuites?.[i]?"ensuite":"common"} onChange={e=>change({bedroomEnsuites:Array.from({length:p.bedrooms},(_,j)=>j===i?e.target.value==="ensuite":p.bedroomEnsuites?.[j]??false)})}><option value="common">Use common bathroom</option><option value="ensuite">Ensuite inside bedroom</option></select></label></>}
      <label><span>Approx. area (m²), including ensuite</span><input aria-label={`Bedroom ${i+1} area`} type="number" min={7.5} max={100} step={.5} disabled={disabled} value={p.bedroomAreasM2?.[i]??p.bedroomAreaM2??14} onChange={e=>{const areas=Array.from({length:p.bedrooms},(_,j)=>j===i?Number(e.target.value):p.bedroomAreasM2?.[j]??p.bedroomAreaM2??14);change({bedroomAreasM2:areas,bedroomAreaM2:areas.reduce((s,a)=>s+a,0)/areas.length});}}/></label></div>)}
    {areasOnly && <div className="ai-area-fields">{(["livingAreaM2","kitchenAreaM2","bathroomAreaM2"] as const).map(key=><label key={key}><span>{key==="livingAreaM2"?"Living / dining":key==="kitchenAreaM2"?"Kitchen":"Each common bathroom"} (m²)</span><input aria-label={key} type="number" min={key==="livingAreaM2"?10:key==="kitchenAreaM2"?6:4} max={300} disabled={disabled} placeholder="Automatic" value={p[key]??""} onChange={e=>change({[key]:e.target.value===""?undefined:Number(e.target.value)})}/></label>)}</div>}
  </div>;
}
