"use client";

import { useEffect,useRef,useState } from "react";
import { createPortal } from "react-dom";
import { FiMaximize2,FiMousePointer,FiSquare,FiCircle,FiType,FiLock,FiUnlock,FiLayers,FiGrid,FiTrash2,FiCornerUpLeft,FiCornerUpRight,FiMove,FiPlus,FiZoomIn,FiZoomOut,FiCheck } from "react-icons/fi";
import type { FloorSketch,ResidentialParameters,RoomUse,SketchPoint } from "@/lib/ai/modeling/allocation";
import { FOOTPRINTS,insidePolygon,inscribedRectangle,polygonArea } from "@/lib/ai/modeling/footprint";
import { resizeSketchLine,circularOutline,arcSegments } from "@/lib/ai/modeling/sketchEditing";
import { sketchRooms } from "@/lib/ai/modeling/sketch";
import { useLayoutDrawingStore } from "@/store/useLayoutDrawingStore";
import { useToolMarkupStore } from "@/store/useToolMarkupStore";
import { componentPreset } from "@/lib/componentCatalog";

type Tool="select"|"outline"|"interior"|"rectangle"|"circle"|"arc"|"room"|"garden"|"pan";
type Pick={index:number;interior:boolean;source:"current"|"below"|"project"};
const uses:RoomUse[]=["bedroom","living","kitchen","dining","study","bathroom","corridor","garage"];
const colors:Record<RoomUse,string>={bedroom:"#60a5fa",living:"#facc15",kitchen:"#fb923c",dining:"#fbbf24",study:"#818cf8",bathroom:"#c084fc",corridor:"#94a3b8",garage:"#64748b"};
const tools:{id:Tool;name:string;icon:React.ReactNode}[]=[{id:"select",name:"Select",icon:<FiMousePointer/>},{id:"outline",name:"Outside",icon:<FiSquare/>},{id:"interior",name:"Inside",icon:<FiLayers/>},{id:"rectangle",name:"Rectangle",icon:<FiSquare/>},{id:"circle",name:"Circle",icon:<FiCircle/>},{id:"arc",name:"Arc",icon:<span aria-hidden="true" className="ai-arc-icon"/>},{id:"room",name:"Room name",icon:<FiType/>},{id:"garden",name:"Garden",icon:<span aria-hidden="true">&#127793;</span>},{id:"pan",name:"Pan",icon:<FiMove/>}];
const help:Record<Tool,string>={select:"Hover to highlight, click to select. Pick a reference layer to copy a line.",outline:"Click outside corners in order. The outline closes automatically.",interior:"Click two endpoints for a partition. Snaps to corners and the floor below.",rectangle:"Click opposite corners to replace the outside outline with a rectangle.",circle:"Click the centre, then the radius. Creates a 24-segment outside outline.",arc:"Click start, end, then the bend. Adds a segmented interior arc.",room:"Click inside a closed room, then enter its name and use.",garden:"Click opposite corners for a garden. Garden areas belong to the ground floor.",pan:"Drag the canvas to move. Use + / - to zoom, or Fit to see everything."};

export default function AiSketchWorkspace({parameters,onChange,onClose,disabled,building}:{parameters:ResidentialParameters;onChange:(p:ResidentialParameters)=>void;onClose:()=>void;disabled:boolean;building?:ReturnType<typeof import("@/lib/ai/modeling/footprint").allocateBuilding>|null}){
  const levels=useLayoutDrawingStore(s=>s.levels),walls=useLayoutDrawingStore(s=>s.walls),equipment=useLayoutDrawingStore(s=>s.mepEquipment),slabs=useLayoutDrawingStore(s=>s.slabs),columns=useLayoutDrawingStore(s=>s.columns),ducts=useLayoutDrawingStore(s=>s.ducts),pipes=useLayoutDrawingStore(s=>s.pipes),doors=useLayoutDrawingStore(s=>s.doors),windows=useLayoutDrawingStore(s=>s.windows),roomsInProject=useLayoutDrawingStore(s=>s.layoutRooms);
  const activeLevel=useToolMarkupStore(s=>s.markupFloorId);
  const source=parameters.footprint==="drawn"?parameters.footprintPoints??[]:FOOTPRINTS[parameters.footprint??"rectangle"];
  const seed:FloorSketch={points:building?.polygon??source.map(p=>({xMm:p.x*(parameters.widthM?parameters.widthM*1000:building?.allocation.internalWidthMm??14000),yMm:p.y*(parameters.lengthM?parameters.lengthM*1000:building?.allocation.internalDepthMm??14000)})),lines:[]};
  const sketches=parameters.sketches??Array.from({length:parameters.variant==="duplex"?2:1},()=>seed);
  const [floor,setFloor]=useState(0),[tool,setTool]=useState<Tool>("select"),[below,setBelow]=useState(true),[anchors,setAnchors]=useState<SketchPoint[]>([]),[selected,setSelected]=useState<Pick|null>(null),[hover,setHover]=useState<string|null>(null),[length,setLength]=useState(""),[error,setError]=useState(""),[pickLayer,setPickLayer]=useState<Pick["source"]>("current"),[projectVisible,setProjectVisible]=useState(true),[projectLevel,setProjectLevel]=useState(activeLevel??levels[0]?.id??""),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[grid,setGrid]=useState(true),[orthogonal,setOrthogonal]=useState(true),[roomPoint,setRoomPoint]=useState<SketchPoint|null>(null),[roomName,setRoomName]=useState(""),[roomUse,setRoomUse]=useState<RoomUse>("bedroom"),[busy,setBusy]=useState(false),[past,setPast]=useState<FloorSketch[][]>([]),[future,setFuture]=useState<FloorSketch[][]>([]);
  const closeRef=useRef<HTMLButtonElement>(null),drag=useRef<{x:number;y:number;pan:{x:number;y:number}}|null>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;closeRef.current?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};document.addEventListener("keydown",handler);return()=>{document.removeEventListener("keydown",handler);previous?.focus();};},[onClose]);
  const current=sketches[Math.min(floor,sketches.length-1)],previous=floor>0?sketches[floor-1]:null;
  const projectWalls=walls.filter(w=>w.levelId===projectLevel);
  const projectPoints=projectVisible?projectWalls.flatMap(w=>[{xMm:w.startXmm,yMm:w.startYmm},{xMm:w.endXmm,yMm:w.endYmm}]):[];
  const allPoints=[...sketches.flatMap(s=>[...s.points,...s.lines.flatMap(l=>[l.start,l.end]),...(s.gardens??[]).flat()]),...projectPoints];
  const minX=Math.min(0,...allPoints.map(p=>p.xMm))-1000,minY=Math.min(0,...allPoints.map(p=>p.yMm))-1000;
  const extent=Math.max(16000,Math.max(0,...allPoints.map(p=>p.xMm))-minX,Math.max(0,...allPoints.map(p=>p.yMm))-minY)+1500,span=extent/zoom;
  const viewX=minX+(extent-span)/2+pan.x,viewY=minY+(extent-span)/2+pan.y;
  const change=(next:FloorSketch[],variant=parameters.variant)=>{setPast(v=>[...v.slice(-29),sketches]);setFuture([]);setError("");onChange({...parameters,variant,sketches:next});};
  const replace=(s:FloorSketch)=>change(sketches.map((old,i)=>i===floor?s:old));
  const resetSelection=()=>{setSelected(null);setAnchors([]);setRoomPoint(null);};
  const lineFor=(pick:Pick)=>{if(pick.source==="project"){const w=projectWalls[pick.index];return w?{start:{xMm:w.startXmm,yMm:w.startYmm},end:{xMm:w.endXmm,yMm:w.endYmm}}:null;}const s=pick.source==="below"?previous:current;if(!s)return null;return pick.interior?s.lines[pick.index]:s.points[pick.index]?{start:s.points[pick.index],end:s.points[(pick.index+1)%s.points.length]}:null;};
  const chooseLine=(index:number,interior:boolean,source:Pick["source"])=>{if(tool!=="select"||pickLayer!==source)return;const pick={index,interior,source},l=lineFor(pick);if(!l)return;setSelected(pick);setLength((Math.hypot(l.end.xMm-l.start.xMm,l.end.yMm-l.start.yMm)/1000).toFixed(2));setRoomPoint(null);};
  const position=(event:React.MouseEvent<SVGSVGElement>|React.PointerEvent<SVGSVGElement>)=>{const matrix=event.currentTarget.getScreenCTM();if(!matrix)return null;const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());return {xMm:point.x,yMm:point.y};};
  const click=(event:React.MouseEvent<SVGSVGElement>)=>{
    if(disabled||tool==="select"||tool==="pan")return;let point=position(event);if(!point)return;
    point={xMm:Math.max(0,Math.min(80000,Math.round(point.xMm/250)*250)),yMm:Math.max(0,Math.min(80000,Math.round(point.yMm/250)*250))};
    const candidates=[...current.points,...current.lines.flatMap(l=>[l.start,l.end]),...(below&&previous?[...previous.points,...previous.lines.flatMap(l=>[l.start,l.end])]:[]),...projectPoints];
    const snap=candidates.reduce<SketchPoint|null>((best,p)=>Math.hypot(p.xMm-point!.xMm,p.yMm-point!.yMm)<span*.014&&(!best||Math.hypot(p.xMm-point!.xMm,p.yMm-point!.yMm)<Math.hypot(best.xMm-point!.xMm,best.yMm-point!.yMm))?p:best,null);
    if(snap&&snap.xMm>=0&&snap.yMm>=0&&snap.xMm<=80000&&snap.yMm<=80000)point=snap;
    else if(orthogonal&&anchors.length&&["interior","outline"].includes(tool)){const a=anchors[0];point=Math.abs(point.xMm-a.xMm)>Math.abs(point.yMm-a.yMm)?{...point,yMm:a.yMm}:{...point,xMm:a.xMm};}
    try{
      if(tool==="room"){const room=sketchRooms(current).find(r=>insidePolygon(point!,r));if(!room)throw new Error("Click inside a closed room.");const label=current.labels?.find(l=>insidePolygon(l.point,room));setRoomPoint(label?.point??point);setRoomName(label?.name??"");setRoomUse(label?.use??"bedroom");return;}
      if(tool==="outline"){if(current.locks?.some(l=>!l.interior))throw new Error("Unlock outside lines before changing the outline.");if(current.points.length>=32)throw new Error("Use up to 32 outside corners.");if(!current.points.some(p=>Math.hypot(p.xMm-point!.xMm,p.yMm-point!.yMm)<1))replace({...current,points:[...current.points,point]});setAnchors([point]);return;}
      if(tool==="garden"&&floor!==0)throw new Error("Select Ground floor to draw a garden.");
      if(!anchors.length){setAnchors([point]);return;}
      const a=anchors[0];
      if(tool==="arc"&&anchors.length===1){setAnchors([a,point]);return;}
      if(tool==="rectangle"||tool==="circle"){
        if(current.locks?.length)throw new Error("Unlock lengths before replacing the outside shape.");
        const points=tool==="circle"?circularOutline(a,Math.hypot(a.xMm-point.xMm,a.yMm-point.yMm)):[{xMm:Math.min(a.xMm,point.xMm),yMm:Math.min(a.yMm,point.yMm)},{xMm:Math.max(a.xMm,point.xMm),yMm:Math.min(a.yMm,point.yMm)},{xMm:Math.max(a.xMm,point.xMm),yMm:Math.max(a.yMm,point.yMm)},{xMm:Math.min(a.xMm,point.xMm),yMm:Math.max(a.yMm,point.yMm)}];
        if(points.some(p=>p.xMm<0||p.yMm<0||p.xMm>80000||p.yMm>80000)||polygonArea(points)<1e6)throw new Error("Draw a shape of at least 1 m² inside the workspace.");replace({...current,points,lines:[],labels:[],locks:[]});
      }else if(tool==="garden"){
        if((current.gardens?.length??0)>=8)throw new Error("Use up to eight garden areas.");const x=Math.min(a.xMm,point.xMm),y=Math.min(a.yMm,point.yMm),w=Math.abs(a.xMm-point.xMm),d=Math.abs(a.yMm-point.yMm);if(w<1000||d<1000)throw new Error("Garden sides need at least 1 m.");const garden=[{xMm:x,yMm:y},{xMm:x+w,yMm:y},{xMm:x+w,yMm:y+d},{xMm:x,yMm:y+d}];if(garden.some(p=>insidePolygon(p,current.points))||current.points.some(p=>insidePolygon(p,garden)))throw new Error("Place the garden outside the house outline.");replace({...current,gardens:[...(current.gardens??[]),garden]});
      }else{
        const additions=tool==="arc"?arcSegments(a,anchors[1],point):[{start:a,end:point}];if(current.lines.length+additions.length>30)throw new Error("Use up to 30 interior wall segments per floor.");if(additions.some(l=>Math.hypot(l.start.xMm-l.end.xMm,l.start.yMm-l.end.yMm)<300))throw new Error("Wall segments need at least 0.3 m.");replace({...current,lines:[...current.lines,...additions]});
      }
      setAnchors([]);setSelected(null);
    }catch(e){setError(e instanceof Error?e.message:"Check the drawing.");}
  };
  const locked=selected?.source==="current"&&current.locks?.some(l=>l.index===selected.index&&l.interior===selected.interior);
  const applyLength=async()=>{if(!selected)return;try{
    if(selected.source!=="project"){if(selected.source==="below")throw new Error("Copy the reference line into this floor before editing.");replace(resizeSketchLine(current,selected.index,selected.interior,Number(length)*1000));}
    else{const w=projectWalls[selected.index],mm=Number(length)*1000;if(w.curved)throw new Error("Edit curved project walls with the project arc tools.");if(!Number.isFinite(mm)||mm<300||mm>80000)throw new Error("Length must be 0.3–80 m.");if(useLayoutDrawingStore.getState().lockedElementKeys.includes(`wall:${w.id}`))throw new Error("This project wall is locked.");const old=Math.hypot(w.endXmm-w.startXmm,w.endYmm-w.startYmm);if(old<1)throw new Error("Wall has no length.");const openings=[...doors,...windows].filter(o=>o.wallId===w.id);if(openings.some(o=>o.positionMm+o.widthMm/2+50>mm))throw new Error("This length would cut off a hosted door or window.");setBusy(true);await useLayoutDrawingStore.getState().updateWall(w.id,{endXmm:w.startXmm+(w.endXmm-w.startXmm)*mm/old,endYmm:w.startYmm+(w.endYmm-w.startYmm)*mm/old});setError("");}
  }catch(e){setError(e instanceof Error?e.message:"Could not update the wall.");}finally{setBusy(false);}};
  const copySelected=()=>{if(!selected)return;const l=lineFor(selected);if(!l)return;if(selected.source==="below"&&!selected.interior&&current.points.length===previous?.points.length){if(current.locks?.length){setError("Unlock outside lengths before copying.");return;}const points=current.points.map((p,i)=>i===selected.index?l.start:i===(selected.index+1)%current.points.length?l.end:p);replace({...current,points});setSelected({...selected,source:"current"});}else{if(current.lines.length>=30){setError("Use up to 30 interior lines.");return;}if([...current.lines,...current.points.map((start,i)=>({start,end:current.points[(i+1)%current.points.length]}))].some(e=>Math.hypot(e.start.xMm-l.start.xMm,e.start.yMm-l.start.yMm)<1&&Math.hypot(e.end.xMm-l.end.xMm,e.end.yMm-l.end.yMm)<1)){setError("This line is already in the drawing.");return;}replace({...current,lines:[...current.lines,l]});setSelected({source:"current",interior:true,index:current.lines.length});}setPickLayer("current");};
  const segment=(a:SketchPoint,b:SketchPoint,index:number,interior:boolean,source:Pick["source"],curvedPath?:string)=>{
    const key=`${source}:${interior}:${index}`,active=selected?.source===source&&selected.index===index&&selected.interior===interior,highlight=hover===key,color=active?"#16a34a":highlight?"#facc15":source==="below"?"#f59e0b":source==="project"?"#94a3b8":interior?"#a78bfa":"#38bdf8",canPick=tool==="select"&&pickLayer===source;
    const isLocked=source==="current"&&current.locks?.some(l=>l.index===index&&l.interior===interior);
    const attrs={stroke:color,strokeWidth:span*(source==="below"?.005:.003),strokeDasharray:source==="below"?`${span*.012} ${span*.008}`:undefined,fill:"none",pointerEvents:"none" as const};
    return <g key={key} className={highlight?"ai-sketch-line-hover":undefined}>{curvedPath?<path d={curvedPath} {...attrs}/>:<line x1={a.xMm} y1={a.yMm} x2={b.xMm} y2={b.yMm} {...attrs}/>}<text x={(a.xMm+b.xMm)/2} y={(a.yMm+b.yMm)/2-span*.009} pointerEvents="none" fontSize={span*.014} textAnchor="middle" fill={color}>{(Math.hypot(b.xMm-a.xMm,b.yMm-a.yMm)/1000).toFixed(1)} m{isLocked?" · locked":""}</text>{canPick&&(curvedPath?<path d={curvedPath} fill="none" stroke="transparent" strokeWidth={span*.018} onMouseEnter={()=>setHover(key)} onMouseLeave={()=>setHover(null)} onClick={e=>{e.stopPropagation();chooseLine(index,interior,source);}}/>:<line x1={a.xMm} y1={a.yMm} x2={b.xMm} y2={b.yMm} stroke="transparent" strokeWidth={span*.018} onMouseEnter={()=>setHover(key)} onMouseLeave={()=>setHover(null)} onClick={e=>{e.stopPropagation();chooseLine(index,interior,source);}}/>)}</g>;
  };
  const drawing=(s:FloorSketch,source:Pick["source"])=> <g className={source==="below"?"ai-sketch-below":"ai-sketch-current"}>
    {s.points.length>=3&&<polygon points={s.points.map(p=>`${p.xMm},${p.yMm}`).join(" ")} fill={source==="below"?"#f59e0b12":"#38bdf80c"} stroke="none" pointerEvents="none"/>}
    {source==="current"&&s.labels?.map((label,i)=>{const room=sketchRooms(s).find(r=>insidePolygon(label.point,r));return <g key={`room${i}`} pointerEvents="none">{room&&<polygon points={room.map(p=>`${p.xMm},${p.yMm}`).join(" ")} fill={`${colors[label.use]}25`}/>}<text x={label.point.xMm} y={label.point.yMm} fontSize={span*.02} textAnchor="middle" fill="currentColor" fontWeight="600">{label.name}</text>{room&&<text x={label.point.xMm} y={label.point.yMm+span*.025} fontSize={span*.014} fill="currentColor" textAnchor="middle">{(polygonArea(room)/1e6).toFixed(1)} m² · {label.use}</text>}</g>;})}
    {s.points.map((a,i)=>segment(a,s.points[(i+1)%s.points.length],i,false,source))}
    {s.lines.map((l,i)=>segment(l.start,l.end,i,true,source))}
    {source==="current"&&s.points.map((p,i)=><circle key={`p${i}`} cx={p.xMm} cy={p.yMm} r={span*.004} fill="#38bdf8" pointerEvents="none"/>)}
    {(s.gardens??[]).map((g,i)=>{const b=inscribedRectangle(g);return <g key={`garden${i}`} pointerEvents="none"><polygon points={g.map(p=>`${p.xMm},${p.yMm}`).join(" ")} fill="#65a30d25" stroke="#65a30d" strokeWidth={span*.002}/><text x={b.xMm+b.widthMm/2} y={b.yMm+b.depthMm/2} textAnchor="middle" fill="#65a30d" fontSize={span*.018}>Garden · {(polygonArea(g)/1e6).toFixed(1)} m²</text></g>;})}
  </g>;
  const projectDrawing=<g className="ai-sketch-project">
    {slabs.filter(s=>s.levelId===projectLevel).map(s=><polygon key={s.id} points={(s.boundary??[]).map(p=>`${p.xMm},${p.yMm}`).join(" ")} fill="#94a3b808" stroke="#94a3b8" strokeWidth={span*.001} pointerEvents="none"/>)}
    {equipment.filter(e=>e.levelId===projectLevel).map(e=><g key={e.id} transform={`translate(${e.xMm} ${e.yMm}) rotate(${e.rotationDeg??0})`} pointerEvents="none"><rect x={-(e.widthMm??600)/2} y={-(e.depthMm??600)/2} width={e.widthMm??600} height={e.depthMm??600} fill={`${e.color??"#94a3b8"}22`} stroke={e.color??"#94a3b8"} strokeWidth={span*.001}/><text fontSize={span*.009} textAnchor="middle" fill="currentColor">{componentPreset(e.familyId??"")?.name??e.category}</text></g>)}
    {columns.filter(c=>c.levelId===projectLevel).map(c=><rect key={c.id} x={c.xMm-c.widthMm/2} y={c.yMm-c.depthMm/2} width={c.widthMm} height={c.depthMm} fill="#64748b" pointerEvents="none"/>)}
    {[...ducts,...pipes].filter(e=>e.levelId===projectLevel).map(e=><line key={e.id} x1={e.startXmm} y1={e.startYmm} x2={e.endXmm} y2={e.endYmm} stroke={"diameterMm"in e?"#14b8a6":"#fb923c"} strokeWidth={span*.002} pointerEvents="none"/>)}
    {projectWalls.map((w,i)=>{const a={xMm:w.startXmm,yMm:w.startYmm},b={xMm:w.endXmm,yMm:w.endYmm};let path:string|undefined;if(w.curved&&w.arcRadiusMm&&w.arcCenterXmm!==undefined&&w.arcCenterYmm!==undefined){const start=w.arcStartAngleDeg??0,sweep=w.arcSweepDeg??((w.arcEndAngleDeg??0)-start),points=Array.from({length:25},(_,i)=>{const angle=(start+sweep*i/24)*Math.PI/180;return `${w.arcCenterXmm!+w.arcRadiusMm!*Math.cos(angle)},${w.arcCenterYmm!+w.arcRadiusMm!*Math.sin(angle)}`;});path=`M${points.join(" L")}`;}return segment(a,b,i,false,"project",path);})}
    {[...doors,...windows].filter(o=>projectWalls.some(w=>w.id===o.wallId)).map(o=>{const w=projectWalls.find(w=>w.id===o.wallId)!,len=Math.hypot(w.endXmm-w.startXmm,w.endYmm-w.startYmm),t=o.positionMm/len;return <circle key={o.id} cx={w.startXmm+(w.endXmm-w.startXmm)*t} cy={w.startYmm+(w.endYmm-w.startYmm)*t} r={span*.005} fill={"sillHeightMm"in o?"#38bdf8":"#fb923c"} pointerEvents="none"/>;})}
    {roomsInProject?.filter(r=>r.levelId===projectLevel).map(r=><text key={r.id} x={r.tagPosMm.xMm} y={r.tagPosMm.yMm} fontSize={span*.016} textAnchor="middle" fill="#94a3b8" pointerEvents="none">{r.name}</text>)}
  </g>;
  return createPortal(<div className="ai-sketch-overlay"><section role="dialog" aria-modal="true" aria-label="House drawing workspace" className="ai-sketch-workspace" onKeyDown={e=>{if(e.key!=="Escape")e.stopPropagation();if(e.key==="Tab"){const targets=[...e.currentTarget.querySelectorAll<HTMLElement>("button:not(:disabled),select:not(:disabled),input:not(:disabled)")],first=targets[0],last=targets[targets.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
    <header><div className="ai-sketch-title"><span className="ai-sketch-title-icon"><FiMaximize2/></span><div><strong>Draw your building</strong><small>Make space for your ideas · dimensions in metres</small></div></div><button ref={closeRef} type="button" className="btn-v-yellow" onClick={onClose}><FiCheck/> Done</button></header>
    <div className="ai-sketch-toolbar"><label>Building<select aria-label="Sketch building type" value={parameters.variant} disabled={disabled} onChange={e=>change(e.target.value==="duplex"&&sketches.length===1?[current,{points:current.points,lines:[]}]:sketches,e.target.value as ResidentialParameters["variant"])}><option value="apartment">Apartment</option><option value="villa">Villa / house</option><option value="duplex">Multi-storey house</option></select></label><label>Floor<select aria-label="Drawing floor" value={floor} onChange={e=>{setFloor(Number(e.target.value));resetSelection();setPickLayer("current");}}>{sketches.map((_,i)=><option key={i} value={i}>{i===0?"Ground floor":`Floor ${i}`}</option>)}</select></label><button type="button" disabled={disabled||sketches.length>=4} onClick={()=>{change([...sketches,{points:current.points,lines:[]}],"duplex");setFloor(sketches.length);resetSelection();}}><FiPlus/> Add floor</button><label><input type="checkbox" checked={below} onChange={e=>{setBelow(e.target.checked);if(!e.target.checked)setPickLayer("current");}}/> Floor below <span className="ai-sketch-legend">amber dashed</span></label><div className="ai-sketch-view-controls"><button type="button" aria-label="Zoom out" onClick={()=>setZoom(v=>Math.max(.5,v/1.25))}><FiZoomOut/></button><span>{Math.round(zoom*100)}%</span><button type="button" aria-label="Zoom in" onClick={()=>setZoom(v=>Math.min(4,v*1.25))}><FiZoomIn/></button><button type="button" onClick={()=>{setZoom(1);setPan({x:0,y:0});}}>Fit</button></div></div>
    <div className="ai-sketch-body"><div className={`ai-sketch-drawing ai-sketch-tool-${tool}`}><svg viewBox={`${viewX} ${viewY} ${span} ${span}`} onClick={click} aria-label="Editable floor drawing" role="img" onPointerDown={e=>{if(tool!=="pan")return;drag.current={x:e.clientX,y:e.clientY,pan};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const rect=e.currentTarget.getBoundingClientRect(),scale=span/Math.min(rect.width,rect.height);setPan({x:drag.current.pan.x-(e.clientX-drag.current.x)*scale,y:drag.current.pan.y-(e.clientY-drag.current.y)*scale});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><defs><pattern id="ai-sketch-grid" width="1000" height="1000" patternUnits="userSpaceOnUse"><path d="M1000 0H0V1000" fill="none" stroke="currentColor" strokeWidth="10" opacity=".1"/></pattern></defs><rect x={viewX} y={viewY} width={span} height={span} fill={grid?"url(#ai-sketch-grid)":"transparent"}/>{projectVisible&&projectDrawing}{below&&previous&&drawing(previous,"below")}{drawing(current,"current")}{anchors.map((a,i)=><circle key={i} cx={a.xMm} cy={a.yMm} r={span*.007} fill="#facc15" stroke="#854d0e" strokeWidth={span*.001}/>)}{roomPoint&&<circle cx={roomPoint.xMm} cy={roomPoint.yMm} r={span*.005} fill="#facc15"/>}</svg><div className="ai-sketch-canvas-note">{tool==="arc"?`${anchors.length}/3 arc points`:tool==="circle"?`${anchors.length}/2 circle points`:help[tool]}<span>250 mm snap · 1 m grid</span></div></div>
    <aside><section className="ai-sketch-card"><h3>Drawing tools</h3><div className="ai-sketch-toolbox">{tools.map(t=><button key={t.id} type="button" disabled={disabled} aria-pressed={tool===t.id} onClick={()=>{setTool(t.id);resetSelection();}}>{t.icon}<span>{t.name}</span></button>)}</div><p>{help[tool]}</p><div className="ai-sketch-checks"><label><input type="checkbox" checked={orthogonal} onChange={e=>setOrthogonal(e.target.checked)}/> Straight / orthogonal snap</label><label><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/><FiGrid/> Grid</label></div></section>
    <section className="ai-sketch-card"><h3>Shapes</h3><div className="ai-suggestion-row">{(["rectangle","l","u"]as const).map(s=><button key={s} type="button" disabled={disabled} onClick={()=>{if(current.locks?.length){setError("Unlock lengths before replacing the shape.");return;}const w=Math.max(4000,...current.points.map(p=>p.xMm)),d=Math.max(4000,...current.points.map(p=>p.yMm));replace({...current,points:FOOTPRINTS[s].map(p=>({xMm:p.x*w,yMm:p.y*d})),lines:[],labels:[],locks:[]});resetSelection();}}>{s==="rectangle"?"Rectangle":`${s.toUpperCase()} shape`}</button>)}</div><p>Rectangle and circle tools draw at your chosen position. Curves use wall segments.</p></section>
    <section className="ai-sketch-card"><h3>Layers & references</h3><label>Select lines from<select aria-label="Pick drawing layer" value={pickLayer} onChange={e=>{setPickLayer(e.target.value as Pick["source"]);setTool("select");resetSelection();}}><option value="current">This floor</option><option value="below" disabled={!previous||!below}>Floor below</option><option value="project" disabled={!projectWalls.length||!projectVisible}>Existing project</option></select></label><label><input type="checkbox" checked={projectVisible} onChange={e=>{setProjectVisible(e.target.checked);if(!e.target.checked)setPickLayer("current");}}/> Show existing project</label>{levels.length>0&&<label>Project level<select aria-label="Existing project level" value={projectLevel} onChange={e=>{setProjectLevel(e.target.value);resetSelection();}}>{levels.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}<p>{projectWalls.length} existing walls · grey. Furniture, floors, openings and MEP appear on this layer.</p>{levels.length>0&&<button type="button" disabled={busy||disabled} onClick={async()=>{setBusy(true);try{const last=[...levels].sort((a,b)=>b.elevationMm-a.elevationMm)[0],level=await useLayoutDrawingStore.getState().addLevel({name:`Floor ${levels.length}`,elevationMm:last.elevationMm+last.heightMm,heightMm:last.heightMm});if(level){setProjectLevel(level.id);setError("");}}catch(e){setError(e instanceof Error?e.message:"Could not add project level.");}finally{setBusy(false);}}}><FiPlus/> Add level to project</button>}{floor>0&&<button type="button" disabled={disabled} onClick={()=>{if(current.locks?.length){setError("Unlock lengths first.");return;}replace({...current,points:previous!.points,lines:[],labels:[],locks:[]});resetSelection();}}>Copy outline from below</button>}</section>
    {selected&&<section className="ai-sketch-card"><h3>{selected.source==="project"?"Existing project wall":selected.source==="below"?"Reference line below":"Selected line"}</h3><label>Length · m<input aria-label="Selected sketch line length in metres" type="number" step=".1" min=".3" max="80" value={length} disabled={!!locked||selected.source==="below"} onChange={e=>setLength(e.target.value)}/></label><button type="button" className="btn-v-yellow" disabled={disabled||busy||!!locked||selected.source==="below"} onClick={applyLength}>{selected.source==="project"?"Save project wall":"Apply length"}</button>{selected.source==="current"?<><button type="button" aria-pressed={!!locked} onClick={()=>{const l=lineFor(selected)!;replace({...current,locks:locked?(current.locks??[]).filter(v=>v.index!==selected.index||v.interior!==selected.interior):[...(current.locks??[]),{index:selected.index,interior:selected.interior,lengthMm:Math.hypot(l.end.xMm-l.start.xMm,l.end.yMm-l.start.yMm)}]});}}>{locked?<FiUnlock/>:<FiLock/>}{locked?"Unlock length":"Lock length"}</button>{selected.interior&&<button type="button" disabled={disabled||!!locked} onClick={()=>{replace({...current,lines:current.lines.filter((_,i)=>i!==selected.index),locks:current.locks?.filter(l=>!l.interior||l.index!==selected.index).map(l=>l.interior&&l.index>selected.index?{...l,index:l.index-1}:l)});resetSelection();}}><FiTrash2/> Delete partition</button>}</>:<button type="button" disabled={disabled} onClick={copySelected}>Copy line into this floor</button>}{selected.source==="project"&&<p>Save updates this wall in the project immediately. Use project Undo to reverse it. Other walls stay in place.</p>}</section>}
    {roomPoint&&<section className="ai-sketch-card"><h3>Name this room</h3><label>Room name<input aria-label="Closed room name" type="text" maxLength={60} value={roomName} placeholder="e.g. Main bedroom" onChange={e=>{setRoomName(e.target.value);const name=e.target.value.toLowerCase();const inferred=uses.find(u=>name.includes(u))??(/office|work/.test(name)?"study":/lounge|family/.test(name)?"living":/wc|toilet|shower/.test(name)?"bathroom":/hall|entry/.test(name)?"corridor":undefined);if(inferred)setRoomUse(inferred);}}/></label><label>Room use<select aria-label="Closed room use" value={roomUse} onChange={e=>setRoomUse(e.target.value as RoomUse)}>{uses.map(u=><option key={u} value={u}>{u[0].toUpperCase()+u.slice(1)}</option>)}</select></label><button className="btn-v-yellow" type="button" disabled={disabled||!roomName.trim()} onClick={()=>{const room=sketchRooms(current).find(r=>insidePolygon(roomPoint,r));if(!room){setError("Room is no longer closed.");return;}replace({...current,labels:[...(current.labels??[]).filter(l=>!insidePolygon(l.point,room)),{point:roomPoint,name:roomName.trim(),use:roomUse}]});setRoomPoint(null);}}>Save room name</button><p>Room use controls furniture and supply/extract ventilation. Water routes go to wet rooms.</p></section>}
    <section className="ai-sketch-card"><h3>Edit drawing</h3><div className="ai-suggestion-row"><button type="button" disabled={disabled||!past.length} onClick={()=>{const previous=past[past.length-1];setFuture(v=>[sketches,...v]);setPast(v=>v.slice(0,-1));setFloor(v=>Math.min(v,previous.length-1));onChange({...parameters,sketches:previous});resetSelection();}}><FiCornerUpLeft/> Undo</button><button type="button" disabled={disabled||!future.length} onClick={()=>{const next=future[0];setPast(v=>[...v,sketches]);setFuture(v=>v.slice(1));setFloor(v=>Math.min(v,next.length-1));onChange({...parameters,sketches:next});resetSelection();}}><FiCornerUpRight/> Redo</button></div><button type="button" disabled={disabled||!!current.locks?.length} onClick={()=>{replace({...current,points:[],lines:[],labels:[],locks:[]});resetSelection();setTool("outline");}}>Redraw this floor</button>{!!current.gardens?.length&&<button type="button" disabled={disabled} onClick={()=>replace({...current,gardens:current.gardens?.slice(0,-1)})}>Remove last garden</button>}<p>Drawing Undo is local. Done returns to chat; Create layout builds a new house alongside existing walls.</p></section>
    {error&&<p role="alert" className="ai-error">{error}</p>}
    </aside></div>
  </section></div>,document.body);
}
