import { z } from "zod";
const point = z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1) }).strict();
export const drawingReferenceSchema = z.object({
  totalAreaM2: z.number().min(1).max(100000).optional(),
  line: z.object({ attachmentIndex: z.number().int().min(0).max(2), pageNumber: z.number().int().min(1).max(10000).optional(), start: point, end: point, lengthMm: z.number().min(10).max(1000000) }).strict()
    .refine(line => Math.hypot(line.start.x-line.end.x, line.start.y-line.end.y) > .001, "Choose two distinct reference points.").optional(),
}).strict().refine(ref => ref.totalAreaM2 !== undefined || ref.line !== undefined, "Provide a total area or known reference length.");
export type DrawingReference = z.infer<typeof drawingReferenceSchema>;
export const DRAWING_GUIDE = "For uploaded plans, reproduce the visible room arrangement, exterior outline, partitions, doors and windows using explicit geometry or suitable recipes. Do not substitute a generic home template. Attached pageNumber identifies the selected original PDF page; only that page is visible. Prefer readable dimension labels and supplied drawingReference. Reference line points are normalized image coordinates (top-left 0,0, bottom-right 1,1); their lengthMm provides scale, and its start is a suitable model origin. If only totalAreaM2 is supplied, estimate relative geometry from the actual enclosed building outline, scale its internal polygon area to the supplied total, preserve proportions, and disclose this approximate reconstruction. Never use the whole image/page rectangle as building area. Without readable dimensions, a reference length or total area, ask once for two identifiable points and their known separation, or the total internal floor area. Keep files with the clarification reply. Use project defaults for heights and routine missing sizes; do not ask a long questionnaire. Record page references and uncertainty. Unclear/occluded topology needs a concise clarification; do not invent a complete unseen floor plan.";
